### PR TITLE
Feature: endpoint to send an confirmation email

### PR DESCRIPTION
**Pull request by ShellyXueHan**
Using Nodemailer package for sending out emails.

### CODE REVIEW

**Comment by ShellyXueHan** [comment]
@patricksimonian fail to rebase onto origin master, not sure why tho... anyway, the feature is just the laster 4 commits (starting from f79c496). Sorry about the mess here!

**Comment by ShellyXueHan** [comment]
@patricksimonian I knew why now... I've rebased to master so there's only desired file changes but I didn't rebase --onto to squash commits. Anyway, please continue with the review. Thx!

**Review by patricksimonian — APPROVED** [review]
Looks good!

**Comment by patricksimonian** [comment]
so rebasing to master only really matters if you require changes from master in a github like flow.

**Comment by patricksimonian** [comment]
also maybe squash these commits ?

**Pull request merged**
